2020-01-11 00:06:59,938 INFO _internal.py: 122  * Restarting with stat
2020-01-11 00:07:01,021 WARNING _internal.py: 122  * Debugger is active!
2020-01-11 00:07:01,038 INFO _internal.py: 122  * Debugger PIN: 217-926-943
2020-01-11 00:07:01,048 INFO _internal.py: 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-01-11 00:07:08,265 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:08] "GET / HTTP/1.1" 200 -
2020-01-11 00:07:11,635 ERROR views.py: 27 Error 10061 connecting to 93.179.119.153:6379. 由于目标计算机积极拒绝，无法连接。.
2020-01-11 00:07:11,726 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:11] "GET /passport/image_code?code_id=1b4f7828-28ee-42aa-90f1-f47600448b6e HTTP/1.1" 200 -
2020-01-11 00:07:11,730 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:11] "GET /favicon.ico HTTP/1.1" 200 -
2020-01-11 00:07:20,817 ERROR views.py: 27 Error 10060 connecting to 93.179.119.153:6379. 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2020-01-11 00:07:20,817 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:20] "GET /passport/image_code?code_id=8130f9f1-5c08-41b6-9dca-d478783e2755 HTTP/1.1" 200 -
2020-01-11 00:07:20,819 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:20] "GET / HTTP/1.1" 200 -
2020-01-11 00:07:23,863 ERROR views.py: 27 Error 10061 connecting to 93.179.119.153:6379. 由于目标计算机积极拒绝，无法连接。.
2020-01-11 00:07:23,863 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:23] "GET /passport/image_code?code_id=8130f9f1-5c08-41b6-9dca-d478783e2755 HTTP/1.1" 200 -
2020-01-11 00:07:23,868 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:23] "GET /favicon.ico HTTP/1.1" 200 -
2020-01-11 00:07:39,578 INFO _internal.py: 122  * Restarting with stat
2020-01-11 00:07:40,583 WARNING _internal.py: 122  * Debugger is active!
2020-01-11 00:07:40,598 INFO _internal.py: 122  * Debugger PIN: 217-926-943
2020-01-11 00:07:40,608 INFO _internal.py: 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-01-11 00:07:42,643 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:42] "GET / HTTP/1.1" 200 -
2020-01-11 00:07:43,001 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:43] "GET /favicon.ico HTTP/1.1" 200 -
2020-01-11 00:07:48,274 ERROR views.py: 27 Error 10061 connecting to 93.179.119.153:6379. 由于目标计算机积极拒绝，无法连接。.
2020-01-11 00:07:48,274 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:48] "GET /passport/image_code?code_id=7d564964-b352-47d1-b258-761c3cad41b2 HTTP/1.1" 200 -
2020-01-11 00:07:56,238 ERROR views.py: 27 Error 10061 connecting to 93.179.119.153:6379. 由于目标计算机积极拒绝，无法连接。.
2020-01-11 00:07:56,238 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:07:56] "GET /passport/image_code?code_id=b8edf116-5436-4387-b822-45b74066e663 HTTP/1.1" 200 -
2020-01-11 00:08:28,111 INFO _internal.py: 122  * Restarting with stat
2020-01-11 00:08:29,117 WARNING _internal.py: 122  * Debugger is active!
2020-01-11 00:08:29,133 INFO _internal.py: 122  * Debugger PIN: 217-926-943
2020-01-11 00:08:29,147 INFO _internal.py: 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-01-11 00:08:32,836 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:08:32] "GET / HTTP/1.1" 200 -
2020-01-11 00:08:33,164 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:08:33] "GET /favicon.ico HTTP/1.1" 200 -
2020-01-11 00:08:48,488 ERROR views.py: 27 Error 10061 connecting to 93.179.119.153:6379. 由于目标计算机积极拒绝，无法连接。.
2020-01-11 00:08:48,488 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:08:48] "GET /passport/image_code?code_id=9276ee5f-17de-41d6-b3c7-04536e6f695c HTTP/1.1" 200 -
2020-01-11 00:30:11,175 INFO _internal.py: 122  * Restarting with stat
2020-01-11 00:30:12,175 WARNING _internal.py: 122  * Debugger is active!
2020-01-11 00:30:12,190 INFO _internal.py: 122  * Debugger PIN: 217-926-943
2020-01-11 00:30:12,205 INFO _internal.py: 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-01-11 00:30:14,955 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:30:14] "GET / HTTP/1.1" 200 -
2020-01-11 00:30:22,702 ERROR views.py: 27 Error while reading from socket: (10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)
2020-01-11 00:30:22,740 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:30:22] "GET /passport/image_code?code_id=784272a4-7c3e-4779-a53f-51a68434aaec HTTP/1.1" 500 -
2020-01-11 00:30:24,578 ERROR views.py: 27 DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
2020-01-11 00:30:24,585 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:30:24] "GET /passport/image_code?code_id=4f0aadbf-4172-44e4-8c18-83b52da7e545 HTTP/1.1" 500 -
2020-01-11 00:30:36,005 INFO _internal.py: 122  * Restarting with stat
2020-01-11 00:30:37,035 WARNING _internal.py: 122  * Debugger is active!
2020-01-11 00:30:37,045 INFO _internal.py: 122  * Debugger PIN: 217-926-943
2020-01-11 00:30:37,060 INFO _internal.py: 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-01-11 00:30:39,175 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:30:39] "GET / HTTP/1.1" 200 -
2020-01-11 00:30:42,717 ERROR views.py: 27 DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
2020-01-11 00:30:42,718 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:30:42] "GET /passport/image_code?code_id=2e0c7b77-7d78-4758-bf3c-cfd62c11550c HTTP/1.1" 200 -
2020-01-11 00:30:44,295 ERROR views.py: 27 Error while reading from socket: (10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)
2020-01-11 00:30:44,295 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:30:44] "GET /passport/image_code?code_id=16267815-90da-48ae-aa5c-9b0618f6008d HTTP/1.1" 200 -
2020-01-11 00:30:46,675 ERROR views.py: 27 DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
2020-01-11 00:30:46,676 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:30:46] "GET /passport/image_code?code_id=d140f15a-2ef9-4784-a73d-400f0decbb68 HTTP/1.1" 200 -
2020-01-11 00:32:13,665 INFO _internal.py: 122  * Restarting with stat
2020-01-11 00:32:14,705 WARNING _internal.py: 122  * Debugger is active!
2020-01-11 00:32:14,725 INFO _internal.py: 122  * Debugger PIN: 217-926-943
2020-01-11 00:32:14,735 INFO _internal.py: 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-01-11 00:32:17,857 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:32:17] "GET / HTTP/1.1" 200 -
2020-01-11 00:32:36,548 ERROR views.py: 27 Error 10060 connecting to 93.179.119.153:6379. 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2020-01-11 00:32:36,548 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:32:36] "GET /passport/image_code?code_id=311c54c1-bd5b-4b64-b932-d0a6d10ae7a6 HTTP/1.1" 200 -
2020-01-11 00:32:52,675 ERROR views.py: 27 Error 10060 connecting to 93.179.119.153:6379. 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2020-01-11 00:32:52,676 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:32:52] "GET /passport/image_code?code_id=1fad4cb7-1cb5-4703-a640-f0a0e74c379c HTTP/1.1" 200 -
2020-01-11 00:32:55,707 ERROR views.py: 27 Error 10061 connecting to 93.179.119.153:6379. 由于目标计算机积极拒绝，无法连接。.
2020-01-11 00:32:55,707 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:32:55] "GET /passport/image_code?code_id=f29f87c6-553f-4275-8cbe-f10da3ea20d8 HTTP/1.1" 200 -
2020-01-11 00:32:55,709 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:32:55] "GET / HTTP/1.1" 200 -
2020-01-11 00:33:11,794 ERROR views.py: 27 Error 10060 connecting to 93.179.119.153:6379. 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2020-01-11 00:33:11,795 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:33:11] "GET /passport/image_code?code_id=6b84ad01-5f56-4074-acd4-3699f07f00b6 HTTP/1.1" 200 -
2020-01-11 00:33:11,800 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:33:11] "GET / HTTP/1.1" 200 -
2020-01-11 00:33:32,249 INFO _internal.py: 122  * Restarting with stat
2020-01-11 00:33:33,331 WARNING _internal.py: 122  * Debugger is active!
2020-01-11 00:33:33,346 INFO _internal.py: 122  * Debugger PIN: 217-926-943
2020-01-11 00:33:33,359 INFO _internal.py: 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-01-11 00:33:38,085 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:33:38] "GET / HTTP/1.1" 200 -
2020-01-11 00:33:40,504 ERROR views.py: 27 DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
2020-01-11 00:33:40,504 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:33:40] "GET /passport/image_code?code_id=6beed2bf-0b3b-41bd-8685-11a8d13c1386 HTTP/1.1" 200 -
2020-01-11 00:33:43,290 ERROR views.py: 27 DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
2020-01-11 00:33:43,290 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:33:43] "GET /passport/image_code?code_id=02011016-ed5f-415a-af2b-f46a8b3f6922 HTTP/1.1" 200 -
2020-01-11 00:33:43,740 ERROR views.py: 27 Error while reading from socket: (10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)
2020-01-11 00:33:43,741 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:33:43] "GET /passport/image_code?code_id=fe855379-d324-4c2c-af09-0a42bdef40a0 HTTP/1.1" 200 -
2020-01-11 00:33:46,015 ERROR views.py: 27 DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
2020-01-11 00:33:46,015 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:33:46] "GET /passport/image_code?code_id=1ea00e1b-e6f3-4061-a5a7-5c3451c7445e HTTP/1.1" 200 -
2020-01-11 00:33:58,537 ERROR views.py: 27 DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
2020-01-11 00:33:58,537 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:33:58] "GET /passport/image_code?code_id=eec6a890-8a2e-46eb-ba21-9377e6659ccd HTTP/1.1" 200 -
2020-01-11 00:33:59,979 ERROR views.py: 27 DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
2020-01-11 00:33:59,980 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:33:59] "GET /passport/image_code?code_id=5c3c4e6e-6b92-4239-8a94-ff93175f4f5c HTTP/1.1" 200 -
2020-01-11 00:34:01,749 ERROR views.py: 27 Error while reading from socket: (10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)
2020-01-11 00:34:01,749 INFO _internal.py: 122 127.0.0.1 - - [11/Jan/2020 00:34:01] "GET /passport/image_code?code_id=78caa269-67b4-47f1-b8e9-3ef5144d0ae1 HTTP/1.1" 200 -
